language: java

services:
  - docker

before_install:
  - docker build -t cloud/test . -f Dockerfile.test
  - docker run -d -t --name unitTestSuite cloud/test

install:
  - skip

script:
  - docker exec unitTestSuite jolie test/submitcode_test.ol
