language: java

services:
  - docker

before_install:
  - docker run -v ${PWD}:/opt/mount --rm --entrypoint cp jolielang/jolie /usr/lib/jolie/jolie.jar /opt/mount/jolie.jar
  - mvn install:install-file -Dfile=jolie.jar -DgroupId=jolie -DartifactId=jolie -Dversion=1.8.2 -Dpackaging=jar

install:
  - (cd parserManager/java/mongo4jolie && mvn package)
  - docker-compose build

before_script:
  - docker-compose up -d
  - sleep 5 # wait for services to get ready
  - docker container ls

script:
  - docker exec parsermanager jolie test/submitcode_test.ol
  - docker exec parsermanager jolie test/auth_test.ol
  - docker exec builder jolie test/build_container_test.ol
