language: java

services:
  - docker

jobs:
  include:
    - stage: build
      before_install:
        - docker run -v ${PWD}:/opt/mount --rm --entrypoint cp jolielang/jolie /usr/lib/jolie/jolie.jar /opt/mount/jolie.jar
        - mvn install:install-file -Dfile=jolie.jar -DgroupId=jolie -DartifactId=jolie -Dversion=1.8.2 -Dpackaging=jar

      install:
        - (cd java/mongo4jolie && mvn package)
        - (cd ParserDeploy && mvn package)
        - docker-compose build

      before_script:
        - docker-compose up -d
        - sleep 5 # wait for services to get ready
        - docker container ls

      # tests
      script:
        #- docker exec parsermanager jolie parserManager/test/submitcode_test.ol
        #- docker exec builder jolie builder/test/build_container_test.ol

    - stage: push to docker hub
      before_install:
        - docker run -v ${PWD}:/opt/mount --rm --entrypoint cp jolielang/jolie /usr/lib/jolie/jolie.jar /opt/mount/jolie.jar
        - mvn install:install-file -Dfile=jolie.jar -DgroupId=jolie -DartifactId=jolie -Dversion=1.8.2 -Dpackaging=jar

      install:
        - (cd java/mongo4jolie && mvn package)
        - (cd ParserDeploy && mvn package)
        - docker-compose build

      script:
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        - docker push porygom/parsermanager:develop
        - docker push porygom/builder:develop
        - docker push porygom/parsergateway:develop
      if: branch = master
