version: "3.7"

networks:
  testnet:
    external:
      name: testnet

services:
  parsermanager:
    build:
      context: .
      dockerfile: ./parserManager/Dockerfile
    image: parsermanager:develop
    ports:
      - "8001:8001"
    environment:
      - MONGODB_HOST=mongodb://mongo_db
      - BUILDER_HOST=builder:8005
    container_name: parsermanager
  builder:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    image: builder:develop
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MONGODB_HOST=mongodb://mongo_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: builder
  parsergateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: parsergateway:develop
    ports:
      - "7999:7999"
    environment:
      - PARSER_HOST=parser:27522
      - LOGSTORE_HOST=logstore:8080
    container_name: parsergateway
    networks:
      - testnet
  mongo_db:
    image: mongo
