version: "3"
services:
  parsermanager:
    build:
      context: .
      dockerfile: ./parserManager/Dockerfile
    image: parsermanager:develop
    ports:
      - "8001:8001"
    environment:
      - MONGODB_HOST=mongodb://mongo_db
      - BUILDER_HOST=builder
    container_name: parsermanager
  builder:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    image: builder:develop
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MONGODB_HOST=mongodb://mongo_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: builder
  mongo_db:
    image: mongo
