version: "3"
services:
  parsermanager:
    build:
      context: .
      dockerfile: ./parserManager/Dockerfile
    image: parsermanager:test
    ports:
      - "8001:8001"
    container_name: parsermanager
  builder:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    image: builder:test
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    container_name: builder
  mongo_db:
    image: mongo
