version: "3.7"

services:
  parsermanager:
    build:
      context: .
      dockerfile: ./parserManager/Dockerfile
    image: porygom/parsermanager:develop
    ports:
      - "8001:8001"
    environment:
      - MONGODB_HOST=mongodb://mongo_db
      - BUILDER_HOST=builder:8005
    container_name: parsermanager
  builder:
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    image: porygom/builder:develop
    ports:
      - "8006:8006"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MONGODB_HOST=mongodb://mongo_db
      - PARSER_REPO=591632264589.dkr.ecr.eu-central-1.amazonaws.com/parsers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: builder
  mongo_db:
    image: mongo
  parsergateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: porygom/parsergateway:develop
    ports:
      - "7999:7999"
    environment:
      - PARSER_HOST=parser:27521
      - LOGSTORE_HOST=logstore:8080
      - ALARMSERVICE_HOST=alarmservice:8005
    container_name: parsergateway
  parser:
    image: porygom/example_parser:develop
    ports:
      - "27521:27521"
